flags: {}
packages:
- '.'
# - location:
#     git: https://github.com/alanz/ghc-mod.git
#     commit: 10025440f1b086ba42fa4c2c8b0d38fa68fa037b
#   extra-dep: true
- location:
    git: https://github.com/alanz/ghc-exactprint.git
    commit: 2341f03ecef20211e6c2a55c29a9df3c2cbb139a
  extra-dep: true
extra-deps:
- Strafunski-StrategyLib-5.0.0.8
- cabal-helper-0.5.1.0
- ghc-mod-5.3.0.0
- rosezipper-0.2
- syz-0.2.0.0
resolver: lts-3.0
