version: 2
jobs:
  build:
    docker:
      - image: alanz/hare-ci
    steps:
      - checkout
      - run: stack --stack-yaml=stack-8.2.2.yaml setup
      - run: stack --stack-yaml=stack-8.2.2.yaml test
